CREATE TABLE system_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE system_face (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    face_img BLOB NOT NULL
);

CREATE TABLE system_capture (
    id INT AUTO_INCREMENT PRIMARY KEY,
    esp_id INT NOT NULL,
    user_id INT NOT NULL,
    door ENUM('entrance', 'exit'),
    `local` INT NOT NULL,
    capture_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE system_esp (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    ssid VARCHAR(255) NOT NULL,
    mac VARCHAR(17) NOT NULL,
    door ENUM('entrance', 'exit') DEFAULT NULL,
    `local` INT NOT NULL,
    register_user_id INT DEFAULT NULL,
    last_start TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);